# Generated by Django 4.2.1 on 2023-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_jobpost_type_alter_jobpost_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='location',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='location',
            field=models.ManyToManyField(null=True, to='app.location'),
        ),
    ]
